import "@testing-library/jest-dom";
import { render, screen } from "@testing-library/react";
import RootLayout, { metadata } from "../app/layout";

describe("RootLayout", () => {
  it("renders children within the layout", () => {
    render(
      <RootLayout>
        <div>Test Content</div>
      </RootLayout>
    );

    // Check if the children are rendered
    expect(screen.getByText("Test Content")).toBeInTheDocument();
  });

  it("sets the correct metadata", () => {
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });
});
